### ISSUE TITLE
Remove eslint

### ISSUE THREAD

**Issue by DominusKelvin** [sailscasts/conference-api#4]
## Steps

- [x] Run `npm uninstall eslint` to uninstall ESLint
- [x] Delete `.eslintrc`
- [x] Delete .eslintignore

**Comment by DominusKelvin** [comment]
@geekiedj can you check off the checkboxes on the tasks?

**Comment by geekiedj** [comment]
> ## Steps
> * [x]  Run `npm uninstall eslint` to uninstall ESLint
> * [x]  Delete `.eslintrc`
> * [x]  Delete .eslintignore
